[package]
name = "easy_emoji"
version = "0.1.0"
authors = ["AbrarNitk <abrar.nitk@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
serde = "~1.0.27"
serde_derive = "~1.0.27"
serde_json = "~1.0.9"